project:
  type: book
  output-dir: docs

book:
  title: "Ozgenur Sensoy Progress Journal"
  repo-url: https://github.com/pjournal/mef07-ozgenursensoy
  chapters:
    - index.qmd
    - assignment1.qmd
    - InClass1.qmd
    - InClass2.qmd
    - ShinyApp.qmd
  page-footer: 
    center: "[MEF BDA 503](https://mef-bda503.github.io)" 
  sharing: [twitter, facebook]

format:
  html:
    theme: cosmo